/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.PasanganController;
import interfaces.CrudInterface;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import models.Pasangan;

/**
 *
 * @author mmohl
 */
public class FormPasangan extends javax.swing.JFrame {
    java.util.List<Pasangan> record = new ArrayList<Pasangan>();
    CrudInterface controller;
    /**
     * Creates new form FormPasangan
     */
    public FormPasangan() {
        super("Form Pasangan");
        initComponents();
        controller = new PasanganController();
                        
        liKategori.setModel(PasanganController.loadModel());
        liKategori.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        
        rbTersedia.setActionCommand("1");
        rbTidak.setActionCommand("0");
        
        try {
            cbPegawai.setModel(PasanganController.loadPegawai());
        } catch (SQLException ex) {
            Logger.getLogger(FormPasangan.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        statusGrup = new javax.swing.ButtonGroup();
        lNama = new javax.swing.JLabel();
        lKategori = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        liKategori = new javax.swing.JList<>();
        lHarga = new javax.swing.JLabel();
        tfHarga = new javax.swing.JTextField();
        rbTersedia = new javax.swing.JRadioButton();
        lStatus = new javax.swing.JLabel();
        rbTidak = new javax.swing.JRadioButton();
        bSimpan = new javax.swing.JButton();
        cbPegawai = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lNama.setText("Nama");

        lKategori.setText("Kategori");

        liKategori.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(liKategori);

        lHarga.setText("Harga");

        statusGrup.add(rbTersedia);
        rbTersedia.setText("Tersedia");

        lStatus.setText("Status");

        statusGrup.add(rbTidak);
        rbTidak.setText("Tidak");

        bSimpan.setText("Simpan");
        bSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSimpanActionPerformed(evt);
            }
        });

        cbPegawai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lHarga)
                            .addComponent(lStatus))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfHarga)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbTersedia)
                                .addGap(18, 18, 18)
                                .addComponent(rbTidak)
                                .addGap(0, 176, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bSimpan)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lKategori)
                            .addComponent(lNama))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbPegawai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNama)
                    .addComponent(cbPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lKategori)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lHarga)
                    .addComponent(tfHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lStatus)
                    .addComponent(rbTersedia)
                    .addComponent(rbTidak))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bSimpan))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimpanActionPerformed
        Pasangan p = new Pasangan();

        try {
            
            p.setId(null);
            p.setId_kategori(multiKategori());
            p.setId_pegawai(convertToId());
            p.setHarga(tfHarga.getText());
            p.setStatus(statusGrup.getSelection().getActionCommand());
            
            controller.Create(p);
            
            JOptionPane.showMessageDialog(rootPane, "Data berhasil ditambahkan");
        
        } catch (SQLException ex) {
            Logger.getLogger(FormPasangan.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_bSimpanActionPerformed
    
    private String convertToId() throws SQLException {
        int id = 0;
        Map<String, Integer> resource = null;
         
        resource = PasanganController.loadPegawaiId();
        id = resource.get(cbPegawai.getSelectedItem().toString());
 
        return String.valueOf(id);
    }
    
    private String multiKategori() {
        int[] k = liKategori.getSelectedIndices();
        String id = "";
        Map<String, Integer> _id = PasanganController.loadModelId();
        
        for (int i = 0; i < k.length; i++) {
            
              if (!id.isEmpty()) {
                  id += ".";
              }
              
              if ( _id.containsKey(liKategori.getModel().getElementAt(k[i])) ) {
                  id += String.valueOf( _id.get(liKategori.getModel().getElementAt(k[i])) );
              }
        }
        return id;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPasangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPasangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPasangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPasangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPasangan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bSimpan;
    private javax.swing.JComboBox<String> cbPegawai;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lHarga;
    private javax.swing.JLabel lKategori;
    private javax.swing.JLabel lNama;
    private javax.swing.JLabel lStatus;
    private javax.swing.JList<String> liKategori;
    private javax.swing.JRadioButton rbTersedia;
    private javax.swing.JRadioButton rbTidak;
    private javax.swing.ButtonGroup statusGrup;
    private javax.swing.JTextField tfHarga;
    // End of variables declaration//GEN-END:variables
}
